# Generated by Django 5.2.13 on 2026-06-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2025/2026', max_length=20, unique=True, verbose_name='Session Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=False, help_text='Only one session can be active at a time', verbose_name='Active Session')),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'db_table': 'academic_sessions',
                'ordering': ['-is_active', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 100 Level, 200 Level', max_length=20, unique=True, verbose_name='Level Name')),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'db_table': 'levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester')], max_length=20, verbose_name='Semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicsession', verbose_name='Academic Session')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semesters',
                'ordering': ['session', 'name'],
                'unique_together': {('name', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(help_text='e.g., CSC101, MTH201', max_length=20, unique=True, verbose_name='Course Code')),
                ('course_title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('credit_unit', models.PositiveIntegerField(help_text='Must be a positive integer', verbose_name='Credit Unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Course')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.level', verbose_name='Level')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.semester', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.studentprofile', verbose_name='Student')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendances',
                'ordering': ['-date'],
                'unique_together': {('student', 'course', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score between 0 and 100', max_digits=5, verbose_name='Score')),
                ('letter_grade', models.CharField(editable=False, max_length=1, verbose_name='Letter Grade')),
                ('grade_point', models.IntegerField(editable=False, verbose_name='Grade Point')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='users.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_carryover', models.BooleanField(default=False, help_text='Mark if this is a carryover course', verbose_name='Carryover')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academics.course', verbose_name='Course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='academics.academicsession', verbose_name='Academic Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='users.studentprofile', verbose_name='Student')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to='academics.semester', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Course Registration',
                'verbose_name_plural': 'Course Registrations',
                'db_table': 'course_registrations',
                'ordering': ['-registration_date'],
                'unique_together': {('student', 'course', 'session', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Enrollment Date')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.level', verbose_name='Level')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.academicsession', verbose_name='Academic Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'db_table': 'student_enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
