# Generated by Django 5.2.13 on 2026-06-15 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='registration',
            field=models.OneToOneField(help_text='The specific course registration attempt for this grade', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='academics.courseregistration', verbose_name='Course Registration'),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
    ]
