# Generated by Django 5.2.13 on 2026-06-15 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_grade_unique_together_grade_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='registration',
            field=models.OneToOneField(help_text='The specific course registration attempt for this grade', on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='academics.courseregistration', verbose_name='Course Registration'),
        ),
    ]
