# Generated by Django 5.2.13 on 2026-07-06 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CGPARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='Cumulative Grade Point Average', max_digits=3, verbose_name='CGPA')),
                ('total_credit_units', models.PositiveIntegerField(verbose_name='Total Credit Units')),
                ('total_quality_points', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Quality Points')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculated At')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgpa_records', to='academics.semester', verbose_name='Semester')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cgpa_records', to='academics.academicsession', verbose_name='Academic Session')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='cgpa_records', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'CGPA Record',
                'verbose_name_plural': 'CGPA Records',
                'db_table': 'cgpa_records',
                'ordering': ['-session', 'semester', '-calculated_at'],
                'unique_together': {('student', 'session', 'semester')},
            },
        ),
    ]
