# Generated by Django 5.2.13 on 2026-06-28 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_department_faculty_permission_attendance_recorded_at_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.programme', verbose_name='Programme'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Additional roles for granular permissions', related_name='users', to='academics.role', verbose_name='RBAC Roles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('admin', 'Admin'), ('lecturer', 'Lecturer')], default='student', max_length=10),
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True, verbose_name='Staff ID')),
                ('rank', models.CharField(choices=[('graduate_assistant', 'Graduate Assistant'), ('assistant_lecturer', 'Assistant Lecturer'), ('lecturer_ii', 'Lecturer II'), ('lecturer_i', 'Lecturer I'), ('senior_lecturer', 'Senior Lecturer'), ('associate_professor', 'Associate Professor'), ('professor', 'Professor')], max_length=30, verbose_name='Academic Rank')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('visiting', 'Visiting'), ('contract', 'Contract')], default='full_time', max_length=20, verbose_name='Employment Type')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_of_employment', models.DateField(auto_now_add=True, verbose_name='Date of Employment')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturers', to='academics.department', verbose_name='Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecturer Profile',
                'verbose_name_plural': 'Lecturer Profiles',
                'db_table': 'lecturer_profiles',
            },
        ),
    ]
