# Generated by Django 5.2.13 on 2026-06-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_studentprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
