# Generated by Django 5.2.13 on 2026-06-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_other_name_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Staff ID'),
        ),
    ]
