# Generated by Django 5.2.13 on 2026-06-28 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_department_faculty_permission_attendance_recorded_at_and_more'),
        ('users', '0005_alter_lecturerprofile_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lecturers', to='academics.department', verbose_name='Department'),
        ),
    ]
