# Generated by Django 5.2.13 on 2026-07-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_type', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer')], max_length=20, verbose_name='Serial Type')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('faculty_code', models.CharField(max_length=10, verbose_name='Faculty Code')),
                ('serial_number', models.IntegerField(verbose_name='Serial Number')),
                ('allocated_at', models.DateTimeField(auto_now_add=True, verbose_name='Allocated At')),
            ],
            options={
                'verbose_name': 'Serial Number',
                'verbose_name_plural': 'Serial Numbers',
                'db_table': 'serial_numbers',
                'ordering': ['-year', 'faculty_code', 'serial_number'],
                'indexes': [models.Index(fields=['serial_type', 'year', 'faculty_code'], name='serial_numb_serial__311fbc_idx')],
                'unique_together': {('serial_type', 'year', 'faculty_code', 'serial_number')},
            },
        ),
    ]
